#!/usr/bin/env bash
set -uo pipefail
REPO_DIR="${CARE_ASD_REPO_DIR:-$HOME/Dung_TDTU/CARE_ASD}"; DATA_ROOT="${CARE_ASD_DATA_ROOT:-$HOME/Dung_TDTU/data/CARE_ASD}"; WORKERS="${CARE_ASD_WORKERS:-12}"; RUN_ID="${1:?run id required}"; BRANCH="research/fp-naa"; cd "$REPO_DIR"
JOB_DIR="outputs/fp_naa/$RUN_ID"; STATE="$JOB_DIR/state.env"; LOG="$JOB_DIR/fp_naa_screening.log"; REPORT_DIR="reports/fp_naa/$RUN_ID"; SERVER_REPORT="reports/server/$RUN_ID.md"; CONFIG="configs/experiment/fp_naa_v1.yaml"; AUDIO_ROOT="$DATA_ROOT/raw/dcase2026/dev/extracted"; BASE_CACHE="$DATA_ROOT/fp_naa/beats_cache/dev/beats_iter3_stereo_10s_v1"; AUG_CACHE="$DATA_ROOT/fp_naa/augmentation_cache/dev/counterfactual_v2"; CHECKPOINT_DIR="$DATA_ROOT/fp_naa/checkpoints/$RUN_ID"; RUNTIME_ENV="$DATA_ROOT/external/fp_naa/runtime.env"; mkdir -p "$JOB_DIR" "$REPORT_DIR" reports/server "$AUG_CACHE" "$CHECKPOINT_DIR"
write_state(){ local status="$1" stage="$2" code="$3"; printf 'run_id=%s\nstatus=%s\nstage=%s\ntask_status=%s\nworkers=%s\nupdated_utc=%s\nlog=%s\n' "$RUN_ID" "$status" "$stage" "$code" "$WORKERS" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$LOG" > "$STATE.tmp"; mv "$STATE.tmp" "$STATE"; }
TASK_STATUS=0; CORE_GATE_PASSED=false; write_state RUNNING setup 99; printf 'FP-NAA C1/C2 screening started at %s\nrun_id=%s\nworkers=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$RUN_ID" "$WORKERS" > "$LOG"
C0_GATE="$(find reports/fp_naa -path '*/c0_baseline/gate.json' -type f -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2-)"; if [ -z "$C0_GATE" ] || ! grep -q '"passed": true' "$C0_GATE"; then printf 'No passed FP-NAA C0 gate found.\n' >> "$LOG"; TASK_STATUS=2; fi
if [ "$TASK_STATUS" -eq 0 ]; then C0_SCORES="$(dirname "$C0_GATE")/freq_rdp8_beam/scores.csv"; bash scripts/server/setup_fp_naa_beats.sh >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then bash scripts/server/fp_naa_conda_run.sh pytest tests/unit/test_fp_naa_adapter.py tests/unit/test_fp_naa_candidate.py -q >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then . "$RUNTIME_ENV"; write_state RUNNING augmentation_cache 99; bash scripts/server/fp_naa_conda_run.sh care-asd fp-naa cache-augmentation --base-cache-dir "$BASE_CACHE" --audio-root "$AUDIO_ROOT" --output-dir "$AUG_CACHE" --config "$CONFIG" --beats-source "$BEATS_SOURCE" --checkpoint "$BEATS_CHECKPOINT" --workers "$WORKERS" --device cuda >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then write_state RUNNING screening 99; bash scripts/server/fp_naa_conda_run.sh care-asd fp-naa screen-dev --base-cache-dir "$BASE_CACHE" --augmentation-cache-dir "$AUG_CACHE" --c0-scores "$C0_SCORES" --output-dir "$REPORT_DIR/screening" --checkpoint-dir "$CHECKPOINT_DIR" --config "$CONFIG" --experiment-id "$RUN_ID" --device cuda --preload-workers "$WORKERS" >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ] && grep -q '"core_screening": true' "$REPORT_DIR/screening/gate.json"; then CORE_GATE_PASSED=true; fi
FINAL_STATUS=DONE; [ "$TASK_STATUS" -eq 0 ] || FINAL_STATUS=FAILED; write_state "$FINAL_STATUS" complete "$TASK_STATUS"; printf 'core_gate_passed=%s\n' "$CORE_GATE_PASSED" >> "$STATE"
{ printf '# FP-NAA C1/C2 screening report\n\nrun_id=%s\nworkers=%s\ntask_status=%s\ncore_gate_passed=%s\nbase_cache=%s\naugmentation_cache=%s\n\n## Gate\n\n```json\n' "$RUN_ID" "$WORKERS" "$TASK_STATUS" "$CORE_GATE_PASSED" "$BASE_CACHE" "$AUG_CACHE"; [ -f "$REPORT_DIR/screening/gate.json" ] && cat "$REPORT_DIR/screening/gate.json" || true; printf '\n```\n\n## Summary\n\n```csv\n'; [ -f "$REPORT_DIR/screening/screening_summary.csv" ] && cat "$REPORT_DIR/screening/screening_summary.csv" || true; printf '\n```\n\n## Log tail\n\n```text\n'; tail -n 100 "$LOG" 2>/dev/null || true; printf '\n```\n'; } > "$SERVER_REPORT"
PUSH_STATUS=0; env -u LD_LIBRARY_PATH -u LD_PRELOAD git add "$REPORT_DIR" "$SERVER_REPORT" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git commit -m "report: add $RUN_ID" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git pull --rebase origin "$BRANCH" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git push origin "HEAD:$BRANCH" || PUSH_STATUS=$?; printf 'push_status=%s\n' "$PUSH_STATUS" >> "$STATE"; exit "$TASK_STATUS"
