#!/usr/bin/env bash
set -uo pipefail
REPO_DIR="${CARE_ASD_REPO_DIR:-$HOME/Dung_TDTU/CARE_ASD}"; DATA_ROOT="${CARE_ASD_DATA_ROOT:-$HOME/Dung_TDTU/data/CARE_ASD}"; WORKERS="${CARE_ASD_WORKERS:-12}"; RUN_ID="${1:?run id required}"; BRANCH="research/fp-naa"; cd "$REPO_DIR"
JOB_DIR="outputs/fp_naa/$RUN_ID"; STATE="$JOB_DIR/state.env"; LOG="$JOB_DIR/fp_naa_baseline.log"; REPORT_DIR="reports/fp_naa/$RUN_ID"; SERVER_REPORT="reports/server/$RUN_ID.md"; CONFIG="configs/experiment/fp_naa_v1.yaml"; MANIFEST="data/manifests/dcase2026_dev.parquet"; AUDIO_ROOT="$DATA_ROOT/raw/dcase2026/dev/extracted"; CACHE_DIR="$DATA_ROOT/fp_naa/beats_cache/dev/beats_iter3_stereo_10s_v1"; RUNTIME_ENV="$DATA_ROOT/external/fp_naa/runtime.env"; mkdir -p "$JOB_DIR" "$REPORT_DIR" reports/server "$CACHE_DIR"
write_state(){ local status="$1" stage="$2" code="$3"; printf 'run_id=%s\nstatus=%s\nstage=%s\ntask_status=%s\nworkers=%s\nupdated_utc=%s\nlog=%s\n' "$RUN_ID" "$status" "$stage" "$code" "$WORKERS" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$LOG" > "$STATE.tmp"; mv "$STATE.tmp" "$STATE"; }
TASK_STATUS=0; GATE_PASSED=false; write_state RUNNING setup 99; printf 'FP-NAA C0 started at %s\nrun_id=%s\nworkers=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$RUN_ID" "$WORKERS" > "$LOG"
bash scripts/server/setup_fp_naa_beats.sh >> "$LOG" 2>&1 || TASK_STATUS=$?
if [ "$TASK_STATUS" -eq 0 ]; then . "$RUNTIME_ENV"; write_state RUNNING cache 99; bash scripts/server/fp_naa_conda_run.sh care-asd fp-naa cache-beats --manifest "$MANIFEST" --audio-root "$AUDIO_ROOT" --output-dir "$CACHE_DIR" --config "$CONFIG" --beats-source "$BEATS_SOURCE" --checkpoint "$BEATS_CHECKPOINT" --workers "$WORKERS" --device cuda >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then write_state RUNNING baseline 99; bash scripts/server/fp_naa_conda_run.sh care-asd fp-naa baseline-dev --cache-dir "$CACHE_DIR" --output-dir "$REPORT_DIR/c0_baseline" --config "$CONFIG" --experiment-id "$RUN_ID" --device cuda >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ] && grep -q '"passed": true' "$REPORT_DIR/c0_baseline/gate.json"; then GATE_PASSED=true; fi
FINAL_STATUS=DONE; [ "$TASK_STATUS" -eq 0 ] || FINAL_STATUS=FAILED; write_state "$FINAL_STATUS" complete "$TASK_STATUS"
{ printf '# FP-NAA C0 strong-baseline report\n\nrun_id=%s\nworkers=%s\ntask_status=%s\ngate_passed=%s\ncache=%s\n\n## Gate\n\n```json\n' "$RUN_ID" "$WORKERS" "$TASK_STATUS" "$GATE_PASSED" "$CACHE_DIR"; [ -f "$REPORT_DIR/c0_baseline/gate.json" ] && cat "$REPORT_DIR/c0_baseline/gate.json" || true; printf '\n```\n\n## Summary\n\n```csv\n'; [ -f "$REPORT_DIR/c0_baseline/summary.csv" ] && cat "$REPORT_DIR/c0_baseline/summary.csv" || true; printf '\n```\n\n## Log tail\n\n```text\n'; tail -n 100 "$LOG" 2>/dev/null || true; printf '\n```\n'; } > "$SERVER_REPORT"
PUSH_STATUS=0; env -u LD_LIBRARY_PATH -u LD_PRELOAD git add "$REPORT_DIR" "$SERVER_REPORT" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git commit -m "report: add $RUN_ID" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git pull --rebase origin "$BRANCH" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git push origin "HEAD:$BRANCH" || PUSH_STATUS=$?; printf 'push_status=%s\n' "$PUSH_STATUS" >> "$STATE"; exit "$TASK_STATUS"
