#!/usr/bin/env bash
set -uo pipefail
REPO_DIR="${CARE_ASD_REPO_DIR:-$HOME/Dung_TDTU/CARE_ASD}"; DATA_ROOT="${CARE_ASD_DATA_ROOT:-$HOME/Dung_TDTU/data/CARE_ASD}"; WORKERS="${CARE_ASD_WORKERS:-12}"; RUN_ID="${1:?run id required}"; cd "$REPO_DIR"
export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 CUBLAS_WORKSPACE_CONFIG=:4096:8
JOB_DIR="outputs/reference_safety/$RUN_ID"; STATE="$JOB_DIR/state.env"; LOG="$JOB_DIR/phase10.log"; REPORT_DIR="reports/reference_safety/$RUN_ID"; SIM_DIR="$REPORT_DIR/simulation"; SERVER_REPORT="reports/server/$RUN_ID.md"; CONFIG="configs/experiment/phase10_reference_safety.yaml"; MANIFEST="data/manifests/dcase2026_dev.parquet"; AUDIO_ROOT="$DATA_ROOT/raw/dcase2026/dev/extracted"; CACHE_ROOT="$DATA_ROOT/reference_safety_cache/dev"; mkdir -p "$JOB_DIR" "$REPORT_DIR" reports/server "$CACHE_ROOT"
LATEST_CACHE_METADATA="$(find "$CACHE_ROOT" -mindepth 2 -maxdepth 2 -type f -name cache.json -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2-)"; CACHE_REUSED=false; if [ -n "$LATEST_CACHE_METADATA" ]; then CACHE_DIR="$(dirname "$LATEST_CACHE_METADATA")"; CACHE_REUSED=true; else CACHE_DIR="$CACHE_ROOT/$RUN_ID"; fi
write_state(){ local status="$1" stage="$2" code="$3"; printf 'run_id=%s\nstatus=%s\nstage=%s\ntask_status=%s\nupdated_utc=%s\nlog=%s\n' "$RUN_ID" "$status" "$stage" "$code" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$LOG" >"$STATE.tmp"; mv "$STATE.tmp" "$STATE"; }
TASK_STATUS=0; write_state RUNNING cache 99; printf 'Phase 10 SAFE-REF started at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$LOG"
if [ "$CACHE_REUSED" = true ]; then printf 'Reusing immutable cache: %s\n' "$CACHE_DIR" >>"$LOG"; else uv run --no-sync care-asd data cache-reference-safety-vectors --train-manifest "$MANIFEST" --train-audio-root "$AUDIO_ROOT" --test-manifest "$MANIFEST" --test-audio-root "$AUDIO_ROOT" --output-dir "$CACHE_DIR" --config "$CONFIG" --workers "$WORKERS" >>"$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then write_state RUNNING simulation 99; uv run --no-sync care-asd reference-safety simulate --manifest "$MANIFEST" --audio-root "$AUDIO_ROOT" --output-dir "$SIM_DIR" --config "$CONFIG" >>"$LOG" 2>&1 || TASK_STATUS=$?; fi
printf '{\n  "cache_dir": "%s",\n  "cache_reused": %s,\n  "run_id": "%s",\n  "schema_version": 1\n}\n' "$CACHE_DIR" "$CACHE_REUSED" "$RUN_ID" >"$REPORT_DIR/run.json"
FINAL_STATUS=DONE; [ "$TASK_STATUS" -eq 0 ] || FINAL_STATUS=FAILED; write_state "$FINAL_STATUS" complete "$TASK_STATUS"
{ printf '# Phase 10 SAFE-REF report\n\nrun_id=%s\ncache=%s\ncache_reused=%s\nworkers=%s\ntask_status=%s\n\n## Gate\n\n```json\n' "$RUN_ID" "$CACHE_DIR" "$CACHE_REUSED" "$WORKERS" "$TASK_STATUS"; [ -f "$SIM_DIR/gate.json" ] && cat "$SIM_DIR/gate.json" || true; printf '\n```\n\n## Log tail\n\n```text\n'; tail -n 80 "$LOG" 2>/dev/null || true; printf '\n```\n'; } >"$SERVER_REPORT"
PUSH_STATUS=0; LD_LIBRARY_PATH="" git add "$REPORT_DIR" "$SERVER_REPORT" && LD_LIBRARY_PATH="" git commit -m "report: add $RUN_ID" && LD_LIBRARY_PATH="" git pull --rebase origin main && LD_LIBRARY_PATH="" git push origin main || PUSH_STATUS=$?; printf 'run_id=%s task_status=%s push_status=%s\n' "$RUN_ID" "$TASK_STATUS" "$PUSH_STATUS" >>"$LOG"; exit "$TASK_STATUS"
