#!/usr/bin/env bash
set -uo pipefail
REPO_DIR="${CARE_ASD_REPO_DIR:-$HOME/Dung_TDTU/CARE_ASD}"; DATA_ROOT="${CARE_ASD_DATA_ROOT:-$HOME/Dung_TDTU/data/CARE_ASD}"; WORKERS="${CARE_ASD_WORKERS:-12}"; RUN_ID="${1:?run id required}"; cd "$REPO_DIR"
export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 CUBLAS_WORKSPACE_CONFIG=:4096:8
JOB_DIR="outputs/reference_safety/$RUN_ID"; STATE="$JOB_DIR/state.env"; LOG="$JOB_DIR/phase10.log"; CACHE_DIR="$DATA_ROOT/reference_safety_cache/dev/$RUN_ID"; REPORT_DIR="reports/reference_safety/$RUN_ID"; SIM_DIR="$REPORT_DIR/simulation"; SERVER_REPORT="reports/server/$RUN_ID.md"; CONFIG="configs/experiment/phase10_reference_safety.yaml"; MANIFEST="data/manifests/dcase2026_dev.parquet"; AUDIO_ROOT="$DATA_ROOT/raw/dcase2026/dev/extracted"; mkdir -p "$JOB_DIR" "$REPORT_DIR" reports/server "$DATA_ROOT/reference_safety_cache/dev"
write_state(){ local status="$1" stage="$2" code="$3"; printf 'run_id=%s\nstatus=%s\nstage=%s\ntask_status=%s\nupdated_utc=%s\nlog=%s\n' "$RUN_ID" "$status" "$stage" "$code" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$LOG" >"$STATE.tmp"; mv "$STATE.tmp" "$STATE"; }
TASK_STATUS=0; write_state RUNNING cache 99; printf 'Phase 10 SAFE-REF started at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$LOG"
uv run --extra torch --extra official-alignment --extra ml care-asd data cache-reference-safety-vectors --train-manifest "$MANIFEST" --train-audio-root "$AUDIO_ROOT" --test-manifest "$MANIFEST" --test-audio-root "$AUDIO_ROOT" --output-dir "$CACHE_DIR" --config "$CONFIG" --workers "$WORKERS" >>"$LOG" 2>&1 || TASK_STATUS=$?
if [ "$TASK_STATUS" -eq 0 ]; then write_state RUNNING simulation 99; uv run --extra torch --extra official-alignment --extra ml care-asd reference-safety simulate --manifest "$MANIFEST" --audio-root "$AUDIO_ROOT" --output-dir "$SIM_DIR" --config "$CONFIG" >>"$LOG" 2>&1 || TASK_STATUS=$?; fi
FINAL_STATUS=DONE; [ "$TASK_STATUS" -eq 0 ] || FINAL_STATUS=FAILED; write_state "$FINAL_STATUS" complete "$TASK_STATUS"
{ printf '# Phase 10 SAFE-REF report\n\nrun_id=%s\ncache=%s\nworkers=%s\ntask_status=%s\n\n## Gate\n\n```json\n' "$RUN_ID" "$CACHE_DIR" "$WORKERS" "$TASK_STATUS"; [ -f "$SIM_DIR/gate.json" ] && cat "$SIM_DIR/gate.json" || true; printf '\n```\n\n## Log tail\n\n```text\n'; tail -n 80 "$LOG" 2>/dev/null || true; printf '\n```\n'; } >"$SERVER_REPORT"
PUSH_STATUS=0; LD_LIBRARY_PATH="" git add "$REPORT_DIR" "$SERVER_REPORT" && LD_LIBRARY_PATH="" git commit -m "report: add $RUN_ID" && LD_LIBRARY_PATH="" git pull --rebase origin main && LD_LIBRARY_PATH="" git push origin main || PUSH_STATUS=$?; printf 'run_id=%s task_status=%s push_status=%s\n' "$RUN_ID" "$TASK_STATUS" "$PUSH_STATUS" >>"$LOG"; exit "$TASK_STATUS"
