#!/usr/bin/env bash
set -uo pipefail
REPO_DIR="${CARE_ASD_REPO_DIR:-$HOME/Dung_TDTU/CARE_ASD}"; DATA_ROOT="${CARE_ASD_DATA_ROOT:-$HOME/Dung_TDTU/data/CARE_ASD}"; WORKERS="${CARE_ASD_WORKERS:-12}"; RUN_ID="${1:?run id required}"; BRANCH="research/fp-naa"; cd "$REPO_DIR"
JOB_DIR="outputs/fp_naa/$RUN_ID"; STATE="$JOB_DIR/state.env"; LOG="$JOB_DIR/fp_naa_confirmatory_lomo.log"; REPORT_DIR="reports/fp_naa/$RUN_ID"; SERVER_REPORT="reports/server/$RUN_ID.md"; CONFIG="configs/experiment/fp_naa_v1.yaml"; BASE_CACHE="$DATA_ROOT/fp_naa/beats_cache/dev/beats_iter3_stereo_10s_v1"; AUG_CACHE="$DATA_ROOT/fp_naa/augmentation_cache/dev/counterfactual_v2"; CHECKPOINT_DIR="$DATA_ROOT/fp_naa/checkpoints/$RUN_ID"; mkdir -p "$JOB_DIR" "$REPORT_DIR" reports/server "$CHECKPOINT_DIR"
write_state(){ local status="$1" stage="$2" code="$3"; printf 'run_id=%s\nstatus=%s\nstage=%s\ntask_status=%s\nworkers=%s\nupdated_utc=%s\nlog=%s\n' "$RUN_ID" "$status" "$stage" "$code" "$WORKERS" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$LOG" > "$STATE.tmp"; mv "$STATE.tmp" "$STATE"; }
TASK_STATUS=0; GATE_PASSED=false; write_state RUNNING setup 99; printf 'FP-NAA five-seed confirmatory LOMO started at %s\nrun_id=%s\nworkers=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$RUN_ID" "$WORKERS" > "$LOG"
LOMO_GATE="$(find reports/fp_naa -path '*/lomo/gate.json' -type f -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2-)"; CONFIRM_GATE="$(find reports/fp_naa -path '*/confirmatory/gate.json' -type f -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2-)"
if [ -z "$LOMO_GATE" ] || ! grep -q '"passed": true' "$LOMO_GATE"; then printf 'No passed latest screening LOMO gate found.\n' >> "$LOG"; TASK_STATUS=2; fi
if [ -z "$CONFIRM_GATE" ] || ! grep -q '"core_confirmatory": true' "$CONFIRM_GATE"; then printf 'No passed latest five-seed core gate found.\n' >> "$LOG"; TASK_STATUS=2; fi
if [ "$TASK_STATUS" -eq 0 ]; then LOMO_DIR="$(dirname "$LOMO_GATE")"; CONFIRM_DIR="$(dirname "$CONFIRM_GATE")"; bash scripts/server/fp_naa_conda_run.sh python -c 'import hashlib,json,sys; digest=lambda p: hashlib.sha256(open(p,"rb").read()).hexdigest(); confirm=json.load(open(sys.argv[1])); assert confirm["lomo_gate_sha256"]==digest(sys.argv[2]), "confirmatory/screening-LOMO artifact mismatch"' "$CONFIRM_DIR/contract.json" "$LOMO_GATE" >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then bash scripts/server/fp_naa_conda_run.sh python -c "import torch; assert torch.__version__ == '2.6.0+cu118'; assert torch.version.cuda == '11.8'; assert torch.cuda.is_available(); print(torch.cuda.get_device_name(0))" >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then bash scripts/server/fp_naa_conda_run.sh pytest tests/unit/test_fp_naa_adapter.py tests/unit/test_fp_naa_candidate.py tests/unit/test_fp_naa_confirmatory.py -q >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ]; then write_state RUNNING confirmatory_lomo 99; bash scripts/server/fp_naa_conda_run.sh care-asd fp-naa confirm-lomo-dev --base-cache-dir "$BASE_CACHE" --augmentation-cache-dir "$AUG_CACHE" --screening-lomo-dir "$LOMO_DIR" --confirmatory-dir "$CONFIRM_DIR" --output-dir "$REPORT_DIR/confirmatory_lomo" --checkpoint-dir "$CHECKPOINT_DIR" --config "$CONFIG" --experiment-id "$RUN_ID" --device cuda --preload-workers "$WORKERS" >> "$LOG" 2>&1 || TASK_STATUS=$?; fi
if [ "$TASK_STATUS" -eq 0 ] && grep -q '"passed": true' "$REPORT_DIR/confirmatory_lomo/gate.json"; then GATE_PASSED=true; fi
FINAL_STATUS=DONE; [ "$TASK_STATUS" -eq 0 ] || FINAL_STATUS=FAILED; write_state "$FINAL_STATUS" complete "$TASK_STATUS"; printf 'gate_passed=%s\n' "$GATE_PASSED" >> "$STATE"
{ printf '# FP-NAA five-seed confirmatory LOMO report\n\nrun_id=%s\nworkers=%s\ntask_status=%s\ngate_passed=%s\n\n## Gate\n\n```json\n' "$RUN_ID" "$WORKERS" "$TASK_STATUS" "$GATE_PASSED"; [ -f "$REPORT_DIR/confirmatory_lomo/gate.json" ] && cat "$REPORT_DIR/confirmatory_lomo/gate.json" || true; printf '\n```\n\n## Fold means\n\n```csv\n'; [ -f "$REPORT_DIR/confirmatory_lomo/confirmatory_lomo_fold_means.csv" ] && cat "$REPORT_DIR/confirmatory_lomo/confirmatory_lomo_fold_means.csv" || true; printf '\n```\n\n## Log tail\n\n```text\n'; tail -n 100 "$LOG" 2>/dev/null || true; printf '\n```\n'; } > "$SERVER_REPORT"
PUSH_STATUS=0; env -u LD_LIBRARY_PATH -u LD_PRELOAD git add "$REPORT_DIR" "$SERVER_REPORT" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git commit -m "report: add $RUN_ID" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git pull --rebase origin "$BRANCH" && env -u LD_LIBRARY_PATH -u LD_PRELOAD git push origin "HEAD:$BRANCH" || PUSH_STATUS=$?; printf 'push_status=%s\n' "$PUSH_STATUS" >> "$STATE"; exit "$TASK_STATUS"
